// <auto-generated />
using System;
using EntityFrameworkcoreCodeFirstApproach.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkcoreCodeFirstApproach.Migrations
{
    [DbContext(typeof(SQLDbContext))]
    [Migration("20200727231308_ThirdMigrationAlterTable")]
    partial class ThirdMigrationAlterTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkcoreCodeFirstApproach.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal?>("Salary")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 4,
                            Email = "john@yahoo.com",
                            Fullname = "John Brown",
                            Salary = 10000m
                        },
                        new
                        {
                            Id = 2,
                            Department = 2,
                            Email = "mary@outlook.com",
                            Fullname = "Mary Smith",
                            Salary = 15000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
